### ISSUE TITLE
Make action robust against API call failures

### ISSUE THREAD

**Issue by EnricoMi** [EnricoMi/download-buildkite-artifact-action#8]
When buildkite API request fails, the action fails straight. We should retry a bit:

https://github.com/horovod/horovod/runs/1251021801?check_suite_focus=true
```
2020-10-14 03:12:01 +0000 - download-buildkite-artifact -  INFO - writing 4888 bytes to /github/workspace/test-results/spark-Spark-PyTests-test-cpu-openmpi-py3_6-tf2_1_0-keras2_3_1-torch1_4_0/artifacts/junit.spark.standalone.test_spark_keras.py.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1379, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1379, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 311, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 280, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/action/download_artifacts.py", line 278, in <module>
    commit, output_path)
  File "/action/download_artifacts.py", line 223, in main
    download_artifacts(buildkite_token, org, pipeline, build_number, artifacts, path_safe_job_names, output_path)
  File "/action/download_artifacts.py", line 125, in download_artifacts
    for artifact in artifacts if artifact['state'] == 'finished'])
  File "/action/download_artifacts.py", line 125, in <listcomp>
    for artifact in artifacts if artifact['state'] == 'finished'])
  File "/action/download_artifacts.py", line 115, in download_artifact
    artifact = buildkite.artifacts().download_artifact(org, pipeline, build_number, job_id, artifact_id)
  File "/usr/local/lib/python3.6/site-packages/pybuildkite/artifacts.py", line 98, in download_artifact
    as_stream=as_stream,
  File "/usr/local/lib/python3.6/site-packages/pybuildkite/client.py", line 131, in get
    as_stream=as_stream,
  File "/usr/local/lib/python3.6/site-packages/pybuildkite/client.py", line 79, in request
    stream=as_stream,
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by EnricoMi** [comment]
Fixed in #19.
